name: flutter_qris
version: 1.0.1+3
description: "A Flutter library for decoding and processing QRIS (Quick Response Code Indonesian Standard) data, designed for payment applications."
homepage: "https://github.com/RohmanBenyRiyanto/qris"
repository: "https://github.com/RohmanBenyRiyanto/qris"
issue_tracker: "https://github.com/RohmanBenyRiyanto/qris/issues"
documentation: "https://github.com/RohmanBenyRiyanto/qris/blob/main/README.md"
environment:
  sdk: "^3.6.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crclib: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

topics:
  - qris
  - qris-library
  - qris-decoder
  - quick-response-code
  - payment-processing
